services:
  mavern-asset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mavern-asset-app
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
