export type ServiceCategory = "all" | "preservation" | "maintenance" | "repairs" | "turnover";

export interface ServiceItem {
  readonly id: string;
  readonly title: string;
  readonly category: ServiceCategory;
  readonly shortDesc: string;
  readonly fullDesc: string;
  readonly features: readonly string[];
  readonly turnaround: string;
  readonly iconName: string;
  readonly imageUrl: string;
  readonly fallbackImage: string;
}

export const SERVICES_DATA: readonly ServiceItem[] = [
  {
    id: "securing",
    title: "Property Securing",
    category: "preservation",
    shortDesc: "Complete property securing, re-keying, lock changes, and board-ups.",
    fullDesc: "Complete property securing including re-keying, lock changes, board-ups, and lockbox installation to prevent unauthorized access.",
    features: ["Re-keying & Deadbolts", "HUD Lockbox Placement", "Polycarbonate Board-Ups", "Door Reinforcement"],
    turnaround: "Same Day / 24h",
    iconName: "ShieldCheck",
    imageUrl: "/assets/cosmic/neon-key-lock.jpg",
    fallbackImage: "/assets/cosmic/neon-key-lock.jpg",
  },
  {
    id: "lawn-care",
    title: "Lawn & Landscape Care",
    category: "maintenance",
    shortDesc: "Regular cuts, trimming, and seasonal yard cleanups.",
    fullDesc: "Regular grass cuts, tree trimming, shrub maintenance, and seasonal yard cleanups to maintain curb appeal and prevent HOA/city code violations.",
    features: ["Grass Mowing & Edging", "Tree & Shrub Trimming", "HOA Code Compliance", "Lot Cleanups"],
    turnaround: "24-48 Hours",
    iconName: "Trees",
    imageUrl: "/assets/cosmic/cosmic-dunes.jpg",
    fallbackImage: "/assets/cosmic/cosmic-dunes.jpg",
  },
  {
    id: "debris-removal",
    title: "Debris Removal",
    category: "preservation",
    shortDesc: "Full interior/exterior trash-outs and hazard removal.",
    fullDesc: "Full interior and exterior trash-outs, hazard removal, and dumping services for foreclosed or vacant properties.",
    features: ["Interior Trash-Outs", "Hazard Disposal", "Exterior Hauling", "Authorized Dumping"],
    turnaround: "24-48 Hours",
    iconName: "Trash2",
    imageUrl: "/assets/cosmic/solar-flare.jpg",
    fallbackImage: "/assets/cosmic/solar-flare.jpg",
  },
  {
    id: "inspections",
    title: "Initial Inspections & Reports",
    category: "preservation",
    shortDesc: "Detailed condition reports, occupancy check & photo logs.",
    fullDesc: "Comprehensive property condition reports, occupancy verification, and damage assessment within 24-48 hours with high-res photo documentation.",
    features: ["Occupancy Verification", "PCR Reports", "GPS Photo Logs", "Damage Bids"],
    turnaround: "24-48 Hours",
    iconName: "ClipboardCheck",
    imageUrl: "/assets/cosmic/cosmic-security-shield.jpg",
    fallbackImage: "/assets/cosmic/cosmic-security-shield.jpg",
  },
  {
    id: "general-repairs",
    title: "General Repairs",
    category: "repairs",
    shortDesc: "Handyman, drywall, plumbing leaks & electrical checks.",
    fullDesc: "Handyman services covering drywall, plumbing leaks, electrical safety checks, and structural repairs for residential and commercial assets.",
    features: ["Drywall Patching", "Plumbing Leaks", "Electrical Safety", "Hardware Fixes"],
    turnaround: "1-3 Days",
    iconName: "Wrench",
    imageUrl: "/assets/cosmic/planet-orbit.jpg",
    fallbackImage: "/assets/cosmic/planet-orbit.jpg",
  },
  {
    id: "exterior-maintenance",
    title: "Exterior Maintenance",
    category: "maintenance",
    shortDesc: "Siding, gutter cleaning, power washing & roof tarping.",
    fullDesc: "Siding repairs, gutter cleaning, pressure washing, and roof tarping/patching to protect property envelope integrity.",
    features: ["Roof Tarping & Patching", "Power Washing", "Gutter Downspouts", "Siding Repairs"],
    turnaround: "24-48 Hours",
    iconName: "Home",
    imageUrl: "/assets/cosmic/mountain-ring-planet.jpg",
    fallbackImage: "/assets/cosmic/mountain-ring-planet.jpg",
  },
  {
    id: "interior-maintenance",
    title: "Interior Maintenance",
    category: "maintenance",
    shortDesc: "Janitorial, deep clean, carpet removal & system checks.",
    fullDesc: "Janitorial services, deep cleaning, carpet removal, and vital system checks to restore interiors to pristine condition.",
    features: ["Deep Janitorial Clean", "Carpet Removal", "HVAC Functionality", "Odor Neutralization"],
    turnaround: "1-2 Days",
    iconName: "Sparkles",
    imageUrl: "/assets/cosmic/nebula-crystal-sphere.jpg",
    fallbackImage: "/assets/cosmic/nebula-crystal-sphere.jpg",
  },
  {
    id: "winterization",
    title: "Winterization",
    category: "preservation",
    shortDesc: "System draining, anti-freeze & dry heat system tests.",
    fullDesc: "Plumbing system draining, anti-freeze application, and dry heat system testing to prevent catastrophic freeze damage during cold months.",
    features: ["Plumbing Line Blow-Outs", "Anti-Freeze Application", "Water Heater Draining", "Dry Heat Tests"],
    turnaround: "Same Day / 24h",
    iconName: "Snowflake",
    imageUrl: "/assets/cosmic/aurora-sunrise.jpg",
    fallbackImage: "/assets/cosmic/aurora-sunrise.jpg",
  },
  {
    id: "renovation",
    title: "Renovation & Refresh",
    category: "turnover",
    shortDesc: "Full painting, flooring, kitchen/bath value upgrades.",
    fullDesc: "Full painting, flooring replacement, and kitchen/bath upgrades designed to maximize ROI and increase asset market value.",
    features: ["Interior/Exterior Paint", "LVP & Hardwood Floors", "Kitchen/Bath Installs", "Fixture Upgrades"],
    turnaround: "3-7 Days",
    iconName: "Paintbrush",
    imageUrl: "/assets/cosmic/valley-sunburst.jpg",
    fallbackImage: "/assets/cosmic/valley-sunburst.jpg",
  },
  {
    id: "safety-repairs",
    title: "Health & Safety Repairs",
    category: "repairs",
    shortDesc: "Mold remediation, trip hazards, railings & code fixes.",
    fullDesc: "Mold remediation, trip hazard removal, railing installation, and municipal code compliance fixes to eliminate liability.",
    features: ["Mold Remediation", "Handrail Installs", "Trip Hazard Leveling", "Code Violation Fixes"],
    turnaround: "24-48 Hours",
    iconName: "AlertTriangle",
    imageUrl: "/assets/cosmic/layered-mist-mountains.jpg",
    fallbackImage: "/assets/cosmic/layered-mist-mountains.jpg",
  },
  {
    id: "turnovers",
    title: "Full Unit Turnovers",
    category: "turnover",
    shortDesc: "End-to-end rental turn preparation: clean, repairs, paint.",
    fullDesc: "End-to-end preparation of rental units for new tenants, including deep cleaning, turn repairs, touch-up painting, and final checklist.",
    features: ["Tenant Turnover Workflow", "Multi-Point Move-In Prep", "Key Reprogramming", "Move-In Ready"],
    turnaround: "2-5 Days",
    iconName: "KeyRound",
    imageUrl: "/assets/cosmic/neon-real-estate-house.jpg",
    fallbackImage: "/assets/cosmic/neon-real-estate-house.jpg",
  },
];
